version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  web:
    image: dockerbuttons/onthelist_semaphore:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DATABASE_HOST=db
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_URL=redis://cache
      - HOST_DOMAIN=https://onthelist.apps.pushbutton.xyz
    volumes:
      - .:/myapp
      - web_gem_cache:/usr/local/bundle
      - web_npm_cache:/myapp/node_modules
    depends_on:
      - db

volumes:
  web_gem_cache:
  web_npm_cache:
