version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.apps.pushbutton.xyz
    volumes:
      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
      - /opt/wallabag/data:/var/www/wallabag/data

  caddy:
    image: caddy/caddy:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ~/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
